import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
const $=id=>document.getElementById(id);let crazyReady=false;
async function initCrazyGames(){try{if(window.CrazyGames?.SDK){await window.CrazyGames.SDK.init();crazyReady=true;$('sdkStatus').textContent='READY'}else $('sdkStatus').textContent='BROWSER MODE'}catch(e){console.warn(e);$('sdkStatus').textContent='BROWSER MODE'}}initCrazyGames();
function cgGameplayStart(){try{window.CrazyGames?.SDK?.game?.gameplayStart?.()}catch(e){}}function cgGameplayStop(){try{window.CrazyGames?.SDK?.game?.gameplayStop?.()}catch(e){}}function cgRoom(roomId,isJoinable=true,inviteParams={}){try{window.CrazyGames?.SDK?.game?.updateRoom?.({roomId,isJoinable,inviteParams})}catch(e){}}function cgLeaveRoom(){try{window.CrazyGames?.SDK?.game?.leftRoom?.()}catch(e){}}async function cgInviteLink(roomId){try{return await window.CrazyGames?.SDK?.game?.inviteLink?.({roomName:roomId})}catch(e){return null}}
let ws=null,playerId=null,room=null,players=new Map(),gameState=null;let local={x:0,y:1.7,z:8,yaw:0,pitch:0,hp:100,ammo:30},keys={},shooting=false,lastShot=0,started=false;
function name(){let n=$('username').value.trim();if(!/^[A-Za-z0-9 ]{3,16}$/.test(n)){$('status').textContent='Username must be 3–16 letters/numbers/spaces.';return null}localStorage.setItem('wls_name',n);return n}$('username').value=localStorage.getItem('wls_name')||'';
function connect(cb){const url=localStorage.getItem('WLS_SERVER_URL')||window.WLS_CONFIG?.multiplayerServerUrl||'ws://localhost:8080';$('status').textContent='Connecting to multiplayer server...';ws=new WebSocket(url);ws.onopen=()=>cb();ws.onmessage=e=>handle(JSON.parse(e.data));ws.onclose=()=>{if(started)$('status').textContent='Connection lost — restart or reconnect.'};ws.onerror=()=>{$('status').textContent='Server unavailable. Start server and try again.'}}
function send(type,data={}){if(ws?.readyState===1)ws.send(JSON.stringify({type,...data}))}
function handle(m){if(m.type==='welcome')playerId=m.id;if(m.type==='room'){room=m.room;cgRoom(room.code,true,{roomCode:room.code});showRoom()}if(m.type==='players'){players=new Map(m.players.map(p=>[p.id,p]));updateRoom()}if(m.type==='started'){cgRoom(room?.code,false,{roomCode:room?.code});startGame(m.state)}if(m.type==='state'){gameState=m;applyState();updateHud()}if(m.type==='kill')feed(`${m.killer} eliminated ${m.victim}`);if(m.type==='matchEnd')endGame(m.winner);if(m.type==='error')$('status').textContent=m.message}
function createRoom(){let n=name();if(!n)return;connect(()=>send('create',{username:n,mode:'tdm',max:10}))}function joinRoom(){let n=name();if(!n)return;let c=prompt('Enter 6-character room code');if(!c)return;connect(()=>send('join',{username:n,code:c.toUpperCase()}))}function quick(){let n=name();if(!n)return;connect(()=>send('quick',{username:n}))}$('create').onclick=createRoom;$('join').onclick=joinRoom;$('quick').onclick=quick;
try{window.CrazyGames?.SDK?.game?.addJoinRoomListener?.(params=>{const c=params?.roomCode||params?.roomName;if(c){const n=name();if(n)connect(()=>send('join',{username:n,code:String(c).toUpperCase()}))}})}catch(e){}
$('practice').onclick=()=>{let n=name();if(!n){$('username').value='Player';localStorage.setItem('wls_name','Player')}startPractice()};
function showRoom(){$('roomBox').classList.remove('hidden');$('roomBox').innerHTML=`<h2>ROOM LOBBY</h2><div class="roomline">CODE: <b>${room.code}</b></div><div id="roomPlayers" class="players"></div><button id="startBtn">START GAME</button> <button id="leaveBtn">LEAVE</button>`;$('startBtn').onclick=()=>send('start');$('leaveBtn').onclick=()=>{cgLeaveRoom();location.reload()};const share=document.createElement('button');share.textContent='SHARE';share.onclick=async()=>{const u=await cgInviteLink(room.code);if(u)navigator.clipboard?.writeText(u)};$('roomBox').appendChild(share);updateRoom()}
function updateRoom(){let el=$('roomPlayers');if(!el)return;el.innerHTML=[...players.values()].map(p=>`${p.username}${p.host?' — HOST':''} (${p.team||'RED'})`).join('<br>')+`<p>${players.size}/${room?.max||10} PLAYERS</p>`}
let scene,camera,renderer,remoteMeshes=new Map();
function setupScene(){scene=new THREE.Scene();scene.background=new THREE.Color(0x07090d);scene.fog=new THREE.Fog(0x07090d,15,90);camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,150);renderer=new THREE.WebGLRenderer({canvas:$('c'),antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));scene.add(new THREE.HemisphereLight(0x9ab0c0,0x17110c,1.2));const moon=new THREE.DirectionalLight(0xb8d0ff,2);moon.position.set(-20,30,10);scene.add(moon);const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:0x24282a,roughness:1}));floor.rotation.x=-Math.PI/2;scene.add(floor);for(let i=0;i<35;i++){let h=2+Math.random()*7,w=2+Math.random()*5,b=new THREE.Mesh(new THREE.BoxGeometry(w,h,2+Math.random()*5),new THREE.MeshStandardMaterial({color:0x252b2f}));b.position.set((Math.random()-.5)*70,h/2,(Math.random()-.5)*70);scene.add(b)}const grid=new THREE.GridHelper(100,50,0x39434a,0x20262b);grid.position.y=.01;scene.add(grid);const gun=new THREE.Mesh(new THREE.BoxGeometry(.22,.2,.8),new THREE.MeshStandardMaterial({color:0x171a1d,metalness:.7}));gun.position.set(.35,-.28,-.65);camera.add(gun);scene.add(camera);addEvents();animate()}
function startGame(state){$('menu').classList.add('hidden');$('game').classList.remove('hidden');started=true;cgGameplayStart();setupScene();gameState=state;local={...local,...state.you}}
function startPractice(){$('menu').classList.add('hidden');$('game').classList.remove('hidden');started=true;setupScene();gameState={practice:true,players:[]};for(let i=0;i<6;i++)gameState.players.push({id:'bot'+i,username:'BOT-'+(i+1),x:(Math.random()-.5)*35,y:1.7,z:(Math.random()-.5)*35,hp:100,team:i%2?'BLUE':'RED'})}
function addEvents(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')local.ammo=30;if(e.code==='Tab')e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);$('c').addEventListener('click',()=>{$('c').requestPointerLock?.()});addEventListener('mousemove',e=>{if(document.pointerLockElement===$('c')){local.yaw-=e.movementX*.002;local.pitch=Math.max(-1.3,Math.min(1.3,local.pitch-e.movementY*.002))}});addEventListener('mousedown',e=>{if(e.button===0)shooting=true});addEventListener('mouseup',e=>{if(e.button===0)shooting=false});addEventListener('blur',()=>shooting=false)}
function shoot(){if(local.ammo<=0||performance.now()-lastShot<110)return;lastShot=performance.now();local.ammo--;const dir=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion);send('shoot',{origin:{x:local.x,y:local.y,z:local.z},dir:{x:dir.x,y:dir.y,z:dir.z}});$('ammo').textContent=`${local.ammo} / 120`}
function applyState(){if(gameState.you)local={...local,...gameState.you}}
function updateHud(){if(!gameState)return;$('timer').textContent=gameState.timer!=null?`${Math.floor(gameState.timer/60)}:${String(gameState.timer%60).padStart(2,'0')}`:'10:00';let r=0,b=0;for(const p of gameState.players||[]){if(p.team==='RED')r+=p.kills||0;else b+=p.kills||0}$('score').textContent=`RED ${r} — ${b} BLUE`;$('hp').textContent=Math.max(0,Math.round(local.hp));$('ammo').textContent=`${local.ammo} / 120`}
function feed(t){let d=document.createElement('div');d.className='feeditem';d.textContent=t;$('feed').prepend(d);setTimeout(()=>d.remove(),4000)}function endGame(w){cgGameplayStop();let d=document.createElement('div');d.className='gameover';d.innerHTML=`${w} TEAM WINS <button id="mainMenuBtn">MAIN MENU</button>`;document.body.appendChild(d);$('mainMenuBtn').onclick=()=>location.reload()}
function animate(){requestAnimationFrame(animate);if(!started)return;const dt=.016,speed=keys.ShiftLeft?8:4;let dx=0,dz=0;if(keys.KeyW)dz-=1;if(keys.KeyS)dz+=1;if(keys.KeyA)dx-=1;if(keys.KeyD)dx+=1;const sin=Math.sin(local.yaw),cos=Math.cos(local.yaw);local.x+=(dx*cos+dz*sin)*speed*dt;local.z+=(dz*cos-dx*sin)*speed*dt;camera.position.set(local.x,local.y,local.z);camera.rotation.set(local.pitch,local.yaw,0,'YXZ');if(shooting)shoot();if(!gameState?.practice)send('input',{x:local.x,y:local.y,z:local.z,yaw:local.yaw,pitch:local.pitch});for(const p of gameState?.players||[]){if(p.id===playerId)continue;let mesh=remoteMeshes.get(p.id);if(!mesh){mesh=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1,4,8),new THREE.MeshStandardMaterial({color:p.team==='BLUE'?0x3e76ff:0xd94b4b}));scene.add(mesh);remoteMeshes.set(p.id,mesh)}mesh.position.set(p.x,p.y-1,p.z)}renderer.render(scene,camera);updateHud()}
