const http=require('http');
const WebSocket=require('ws'),crypto=require('crypto');
const PORT=Number(process.env.PORT||8080),HOST='0.0.0.0';
const httpServer=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({ok:true,game:'WARZONE: LAST STAND',websocket:true,version:'3.0',players:true,matchmaking:true}))});
const wss=new WebSocket.Server({server:httpServer}),rooms=new Map(),clients=new Map(),queue=[];
const id=()=>crypto.randomBytes(8).toString('hex');
function code(){let c;do{c=crypto.randomBytes(3).toString('hex').toUpperCase()}while(rooms.has(c));return c}
function send(ws,m){if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(m))}
function broadcast(r,m){for(const p of r.players.values())send(p.ws,m)}
function pub(p){return{id:p.id,username:p.username,team:p.team,host:p.host,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,kills:p.kills,deaths:p.deaths,ammo:p.ammo}}
function state(r,p){return{type:'state',players:[...r.players.values()].map(pub),you:pub(p),timer:Math.max(0,Math.ceil((r.end-Date.now())/1000)),score:{red:r.redScore,blue:r.blueScore}}}
function lobby(r){broadcast(r,{type:'players',players:[...r.players.values()].map(pub)})}
function validName(n){return typeof n==='string'&&/^[A-Za-z0-9 ]{3,16}$/.test(n.trim())}
function team(r){let red=0,blue=0;for(const p of r.players.values())p.team==='RED'?red++:blue++;return red<=blue?'RED':'BLUE'}
function mk(ws,n,r,host=false){return{id:id(),ws,username:n.trim(),room:r,host,team:team(r),x:0,y:1.7,z:0,yaw:0,pitch:0,hp:100,kills:0,deaths:0,ammo:30,lastShot:0}}
function reset(p){p.hp=100;p.ammo=30;p.x=(Math.random()-.5)*70;p.y=1.7;p.z=(Math.random()-.5)*70;p.yaw=Math.random()*Math.PI*2;p.pitch=0}
function makeRoom(players,quick=false){const r={code:code(),max:10,mode:'tdm',duration:600,players:new Map(),started:false,end:0,tick:null,redScore:0,blueScore:0,quick,created:Date.now()};rooms.set(r.code,r);players.forEach((item,i)=>{const p=mk(item.ws,item.username,r,i===0);reset(p);r.players.set(p.id,p);clients.set(item.ws,p)});lobby(r);for(const p of r.players.values()){send(p.ws,{type:'welcome',id:p.id});send(p.ws,{type:'room',room:{code:r.code,max:r.max,mode:r.mode,quick:r.quick}})};return r}
function start(r){if(r.started||r.players.size<2)return;r.started=true;r.end=Date.now()+r.duration*1000;r.redScore=0;r.blueScore=0;for(const p of r.players.values()){p.kills=0;p.deaths=0;reset(p)}broadcast(r,{type:'matchFound',players:r.players.size});for(const p of r.players.values())send(p.ws,{type:'started',state:state(r,p)});r.tick=setInterval(()=>{if(Date.now()>=r.end){end(r);return}for(const p of r.players.values())if(p.ws)send(p.ws,state(r,p))},100)}
function end(r){if(!rooms.has(r.code))return;clearInterval(r.tick);r.tick=null;r.started=false;const winner=r.redScore===r.blueScore?'DRAW':r.redScore>r.blueScore?'RED':'BLUE';broadcast(r,{type:'matchEnd',winner,score:{red:r.redScore,blue:r.blueScore}})}
function create(ws,n){const r=makeRoom([{ws,username:n}],false);send(ws,{type:'roomReady'})}
function join(ws,n,c){const r=rooms.get(c);if(!r)return send(ws,{type:'error',message:'ROOM NOT FOUND'});if(r.started)return send(ws,{type:'error',message:'MATCH ALREADY STARTED'});if(r.players.size>=r.max)return send(ws,{type:'error',message:'ROOM IS FULL'});if([...r.players.values()].some(p=>p.username.toLowerCase()===n.toLowerCase()))return send(ws,{type:'error',message:'USERNAME ALREADY IN ROOM'});const p=mk(ws,n,r,false);r.players.set(p.id,p);clients.set(ws,p);send(ws,{type:'welcome',id:p.id});send(ws,{type:'room',room:{code:r.code,max:r.max,mode:r.mode,quick:r.quick}});lobby(r)}
function enqueue(ws,n){if(queue.some(x=>x.ws===ws))return;queue.push({ws,username:n,at:Date.now()});send(ws,{type:'matchmaking',queued:queue.length,message:'Searching for real players…'});tryMatch()}
function tryMatch(){while(queue.length>=2){const group=queue.splice(0,Math.min(10,queue.length));const r=makeRoom(group,true);sendGroup(r,'matchmaking',{queued:r.players.size,message:`MATCH FOUND — ${r.players.size} REAL PLAYERS`});setTimeout(()=>{if(r.players.size>=2&&!r.started)start(r)},1800);if(group.length===10)continue;break}}
function sendGroup(r,type,data){for(const p of r.players.values())send(p.ws,{type,...data})}
function damage(r,a,origin,dir){if(!origin||!dir||a.hp<=0||Date.now()-a.lastShot<90||a.ammo<=0)return;a.lastShot=Date.now();a.ammo--;const len=Math.hypot(dir.x,dir.y,dir.z)||1;dir={x:dir.x/len,y:dir.y/len,z:dir.z/len};let hit=null,best=.72;for(const p of r.players.values()){if(p===a||p.hp<=0||p.team===a.team)continue;const vx=p.x-origin.x,vy=(p.y-.65)-origin.y,vz=p.z-origin.z,t=vx*dir.x+vy*dir.y+vz*dir.z;if(t<0||t>110)continue;const px=origin.x+dir.x*t,py=origin.y+dir.y*t,pz=origin.z+dir.z*t,d=Math.hypot(p.x-px,(p.y-.65)-py,p.z-pz);if(d<best){best=d;hit=p}}if(hit){hit.hp-=34;if(hit.hp<=0){hit.hp=0;hit.deaths++;a.kills++;a.team==='RED'?r.redScore++:r.blueScore++;broadcast(r,{type:'kill',killer:a.username,victim:hit.username});setTimeout(()=>{if(r.started&&r.players.has(hit.id)){reset(hit);send(hit.ws,{type:'respawn',state:pub(hit)})}},1500)}}}
const heartbeat=setInterval(()=>{for(const ws of wss.clients){if(ws.isAlive===false){ws.terminate();continue}ws.isAlive=false;ws.ping()}},30000);
wss.on('connection',ws=>{ws.isAlive=true;ws.on('pong',()=>ws.isAlive=true);send(ws,{type:'hello'});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return send(ws,{type:'error',message:'Invalid message'})};
if(m.type==='create'){if(validName(m.username))create(ws,m.username.trim());else send(ws,{type:'error',message:'Invalid username'})}
else if(m.type==='join'){if(validName(m.username))join(ws,m.username.trim(),String(m.code||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase());else send(ws,{type:'error',message:'Invalid username'})}
else if(m.type==='quick'){if(validName(m.username))enqueue(ws,m.username.trim());else send(ws,{type:'error',message:'Invalid username'})}
else if(m.type==='start'){const p=clients.get(ws);if(p&&p.host)start(p.room)}
else {const p=clients.get(ws);if(!p)return;if(m.type==='input'&&p.room.started&&p.hp>0){p.x=Math.max(-48,Math.min(48,Number(m.x)||0));p.y=1.7;p.z=Math.max(-48,Math.min(48,Number(m.z)||0));p.yaw=Number(m.yaw)||0;p.pitch=Math.max(-1.4,Math.min(1.4,Number(m.pitch)||0))}if(m.type==='shoot'&&p.room.started)damage(p.room,p,m.origin,m.dir)}});
ws.on('close',()=>{for(let i=queue.length-1;i>=0;i--)if(queue[i].ws===ws)queue.splice(i,1);const p=clients.get(ws);if(!p)return;const r=p.room;r.players.delete(p.id);clients.delete(ws);if(p.host){const np=[...r.players.values()][0];if(np){np.host=true;send(np.ws,{type:'hostTransferred',message:'You are now the host.'})}}if(!r.players.size){clearInterval(r.tick);rooms.delete(r.code)}else lobby(r)})});
httpServer.listen(PORT,HOST,()=>console.log(`WARZONE: LAST STAND server v3 running on port ${PORT}`));