const http=require('http');
const WebSocket=require('ws'),crypto=require('crypto');
const PORT=Number(process.env.PORT||8080);
const HOST='0.0.0.0';
const httpServer=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:true,game:'WARZONE: LAST STAND',websocket:true}));});
const wss=new WebSocket.Server({server:httpServer});
const rooms=new Map(), clients=new Map();
function id(){return crypto.randomBytes(8).toString('hex')}
function code(){let c;do{c=crypto.randomBytes(3).toString('hex').toUpperCase()}while(rooms.has(c));return c}
function send(c,m){if(c&&c.readyState===1)c.send(JSON.stringify(m))}
function broadcast(room,m){room.players.forEach(p=>send(p.ws,m))}
function publicPlayer(p){return {id:p.id,username:p.username,team:p.team,host:p.host,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,kills:p.kills,deaths:p.deaths}}
function publicPlayers(room){return [...room.players.values()].map(publicPlayer)}
function stateFor(room,p){return {type:'state',players:publicPlayers(room),you:publicPlayer(p),timer:Math.max(0,Math.ceil((room.end-Date.now())/1000))}}
function lobby(room){broadcast(room,{type:'players',players:publicPlayers(room)})}
function balancedTeam(room){let r=[...room.players.values()].filter(p=>p.team==='RED').length,b=[...room.players.values()].filter(p=>p.team==='BLUE').length;return r<=b?'RED':'BLUE'}
function start(room){if(room.started||room.players.size<2)return;room.started=true;room.end=Date.now()+room.duration*1000;room.players.forEach(p=>{p.hp=100;p.kills=0;p.deaths=0;p.x=(Math.random()-.5)*30;p.y=1.7;p.z=(Math.random()-.5)*30;p.ammo=30});room.players.forEach(p=>send(p.ws,{type:'started',state:stateFor(room,p)}));room.tick=setInterval(()=>{if(Date.now()>=room.end){end(room);return}room.players.forEach(p=>send(p.ws,stateFor(room,p)))},100)}
function end(room){if(!rooms.has(room.code))return;clearInterval(room.tick);room.started=false;let r=0,b=0;room.players.forEach(p=>{if(p.team==='RED')r+=p.kills;else b+=p.kills});broadcast(room,{type:'matchEnd',winner:r>=b?'RED':'BLUE'})}
function validName(n){return typeof n==='string'&&/^[A-Za-z0-9 ]{3,16}$/.test(n.trim())}
function player(ws,n,room,host=false){return{id:id(),ws,username:n.trim(),room,host,team:balancedTeam(room),x:0,y:1.7,z:0,yaw:0,pitch:0,hp:100,kills:0,deaths:0,ammo:30,lastShot:0}}
function create(ws,n){let room={code:code(),max:10,mode:'tdm',duration:600,players:new Map(),started:false};rooms.set(room.code,room);let p=player(ws,n,room,true);room.players.set(p.id,p);clients.set(ws,p);send(ws,{type:'welcome',id:p.id});send(ws,{type:'room',room:{code:room.code,max:room.max,mode:room.mode}});lobby(room)}
function join(ws,n,c){let room=rooms.get(c);if(!room)return send(ws,{type:'error',message:'ROOM NOT FOUND'});if(room.started)return send(ws,{type:'error',message:'MATCH ALREADY STARTED'});if(room.players.size>=room.max)return send(ws,{type:'error',message:'ROOM IS FULL'});if([...room.players.values()].some(p=>p.username.toLowerCase()===n.trim().toLowerCase()))return send(ws,{type:'error',message:'USERNAME ALREADY IN ROOM'});let p=player(ws,n,room);room.players.set(p.id,p);clients.set(ws,p);send(ws,{type:'welcome',id:p.id});send(ws,{type:'room',room:{code:room.code,max:room.max,mode:room.mode}});lobby(room)}
function damage(room,attacker,origin,dir){if(!origin||!dir)return;let now=Date.now();if(now-attacker.lastShot<90||attacker.ammo<=0||attacker.hp<=0)return;attacker.lastShot=now;attacker.ammo--;let hit=null,best=2.0;for(let p of room.players.values()){if(p===attacker||p.hp<=0)continue;if(room.mode==='tdm'&&p.team===attacker.team)continue;let vx=p.x-origin.x,vy=p.y-origin.y,vz=p.z-origin.z,t=vx*dir.x+vy*dir.y+vz*dir.z;if(t<0||t>80)continue;let px=origin.x+dir.x*t,py=origin.y+dir.y*t,pz=origin.z+dir.z*t,d=Math.hypot(p.x-px,p.y-py,p.z-pz);if(d<best){best=d;hit=p}}if(hit){hit.hp-=34;if(hit.hp<=0){hit.hp=0;hit.deaths++;attacker.kills++;broadcast(room,{type:'kill',killer:attacker.username,victim:hit.username});setTimeout(()=>{if(room.started){hit.hp=100;hit.x=(Math.random()-.5)*30;hit.z=(Math.random()-.5)*30}},1500)}}}
const heartbeat=setInterval(()=>{for(const ws of wss.clients){if(ws.isAlive===false){ws.terminate();continue}ws.isAlive=false;ws.ping()}},30000);
wss.on('connection',ws=>{ws.isAlive=true;ws.on('pong',()=>{ws.isAlive=true});send(ws,{type:'hello'});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return send(ws,{type:'error',message:'Invalid message'})}if(m.type==='create'){if(validName(m.username))create(ws,m.username);else send(ws,{type:'error',message:'Invalid username'})}else if(m.type==='join'){if(validName(m.username))join(ws,m.username,String(m.code||'').toUpperCase());else send(ws,{type:'error',message:'Invalid username'})}else if(m.type==='quick'){if(!validName(m.username))return send(ws,{type:'error',message:'Invalid username'});let room=[...rooms.values()].find(r=>!r.started&&r.players.size<r.max);room?join(ws,m.username,room.code):create(ws,m.username)}else{let p=clients.get(ws);if(!p)return;if(m.type==='start'){if(p.host)start(p.room)}if(m.type==='input'&&!p.room.started)return;if(m.type==='input'){p.x=Number(m.x)||0;p.y=1.7;p.z=Number(m.z)||0;p.yaw=Number(m.yaw)||0;p.pitch=Number(m.pitch)||0}if(m.type==='shoot'&&p.room.started)damage(p.room,p,m.origin,m.dir)}});ws.on('close',()=>{let p=clients.get(ws);if(!p)return;let r=p.room;r.players.delete(p.id);clients.delete(ws);if(p.host){let np=r.players.values().next().value;if(np){np.host=true;send(np.ws,{type:'hostTransferred',message:'You are now the host.'})}}if(!r.players.size){clearInterval(r.tick);rooms.delete(r.code)}else lobby(r)})});
wss.on('close',()=>clearInterval(heartbeat));
httpServer.listen(PORT,HOST,()=>console.log(`WARZONE: LAST STAND server running on port ${PORT}`));