const http=require('http');
const WebSocket=require('ws'),crypto=require('crypto');
const PORT=Number(process.env.PORT||8080),HOST='0.0.0.0';
const httpServer=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:true,game:'WARZONE: LAST STAND',websocket:true,version:'2.0'}));});
const wss=new WebSocket.Server({server:httpServer}),rooms=new Map(),clients=new Map();
const id=()=>crypto.randomBytes(8).toString('hex');
function code(){let c;do{c=crypto.randomBytes(3).toString('hex').toUpperCase()}while(rooms.has(c));return c}
function send(c,m){if(c&&c.readyState===1)c.send(JSON.stringify(m))} function broadcast(r,m){r.players.forEach(p=>send(p.ws,m))}
function pub(p){return{id:p.id,username:p.username,team:p.team,host:p.host,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,kills:p.kills,deaths:p.deaths,ammo:p.ammo,bot:p.bot}}
function state(r,p){return{type:'state',players:[...r.players.values()].map(pub),you:pub(p),timer:Math.max(0,Math.ceil((r.end-Date.now())/1000)),score:{red:r.redScore,blue:r.blueScore}}}
function lobby(r){broadcast(r,{type:'players',players:[...r.players.values()].map(pub)})}
function team(r){let red=[...r.players.values()].filter(p=>p.team==='RED').length,blue=[...r.players.values()].filter(p=>p.team==='BLUE').length;return red<=blue?'RED':'BLUE'}
function validName(n){return typeof n==='string'&&/^[A-Za-z0-9 ]{3,16}$/.test(n.trim())}
function mkPlayer(ws,n,r,host=false,bot=false){return{id:id(),ws,username:n.trim(),room:r,host,bot,team:team(r),x:(Math.random()-.5)*42,y:1.7,z:(Math.random()-.5)*42,yaw:Math.random()*Math.PI*2,pitch:0,hp:100,kills:0,deaths:0,ammo:30,lastShot:0,aiNext:0,aiTarget:null}}
function create(ws,n,quick=false){let r={code:code(),max:10,mode:'tdm',duration:600,players:new Map(),started:false,end:0,tick:null,quick,redScore:0,blueScore:0};rooms.set(r.code,r);let p=mkPlayer(ws,n,r,true,false);r.players.set(p.id,p);clients.set(ws,p);send(ws,{type:'welcome',id:p.id});send(ws,{type:'room',room:{code:r.code,max:r.max,mode:r.mode,quick:r.quick}});lobby(r);if(quick){send(ws,{type:'quickWaiting',message:'Searching for real players… bots will join if matchmaking takes too long.'});setTimeout(()=>quickStart(r),12000)}}
function join(ws,n,c){let r=rooms.get(c);if(!r)return send(ws,{type:'error',message:'ROOM NOT FOUND'});if(r.started)return send(ws,{type:'error',message:'MATCH ALREADY STARTED'});if(r.players.size>=r.max)return send(ws,{type:'error',message:'ROOM IS FULL'});if([...r.players.values()].some(p=>p.username.toLowerCase()===n.trim().toLowerCase()))return send(ws,{type:'error',message:'USERNAME ALREADY IN ROOM'});let p=mkPlayer(ws,n,r,false,false);r.players.set(p.id,p);clients.set(ws,p);send(ws,{type:'welcome',id:p.id});send(ws,{type:'room',room:{code:r.code,max:r.max,mode:r.mode,quick:r.quick}});lobby(r);if(r.quick&&[...r.players.values()].filter(p=>!p.bot).length>=2)quickStart(r)}
function addBot(r){if(r.players.size>=r.max)return;let n='BOT-'+String([...r.players.values()].filter(p=>p.bot).length+1);let p=mkPlayer(null,n,r,false,true);r.players.set(p.id,p)}
function quickStart(r){if(!r||r.started)return;if(![...r.players.values()].some(p=>!p.bot))return;while(r.players.size<6)addBot(r);start(r)}
function resetPlayer(p){p.hp=100;p.ammo=30;p.x=(Math.random()-.5)*42;p.z=(Math.random()-.5)*42;p.y=1.7;p.yaw=Math.random()*Math.PI*2;p.pitch=0}
function start(r){if(r.started||r.players.size<2)return;r.started=true;r.end=Date.now()+r.duration*1000;r.redScore=r.blueScore=0;r.players.forEach(resetPlayer);r.players.forEach(p=>send(p.ws,{type:'started',state:state(r,p)}));r.tick=setInterval(()=>{if(Date.now()>=r.end){end(r);return}botThink(r);r.players.forEach(p=>{if(!p.bot)send(p.ws,state(r,p))})},100)}
function end(r){if(!rooms.has(r.code))return;clearInterval(r.tick);r.started=false;let winner=r.redScore===r.blueScore?'DRAW':(r.redScore>r.blueScore?'RED':'BLUE');broadcast(r,{type:'matchEnd',winner,score:{red:r.redScore,blue:r.blueScore}})}
function kill(r,a,v){v.hp=0;v.deaths++;a.kills++;if(a.team==='RED')r.redScore++;else r.blueScore++;broadcast(r,{type:'kill',killer:a.username,victim:v.username});setTimeout(()=>{if(r.started){resetPlayer(v);send(v.ws,{type:'respawn',state:pub(v)})}},1500)}
function damage(r,a,origin,dir){if(!origin||!dir||a.hp<=0||Date.now()-a.lastShot<95||a.ammo<=0)return;a.lastShot=Date.now();a.ammo--;let len=Math.hypot(dir.x,dir.y,dir.z)||1;dir={x:dir.x/len,y:dir.y/len,z:dir.z/len};let hit=null,best=.72;for(const p of r.players.values()){if(p===a||p.hp<=0||p.team===a.team)continue;let vx=p.x-origin.x,vy=(p.y-.7)-origin.y,vz=p.z-origin.z,t=vx*dir.x+vy*dir.y+vz*dir.z;if(t<0||t>90)continue;let px=origin.x+dir.x*t,py=origin.y+dir.y*t,pz=origin.z+dir.z*t,d=Math.hypot(p.x-px,(p.y-.7)-py,p.z-pz);if(d<best){best=d;hit=p}}if(hit){hit.hp-=34;if(hit.hp<=0)kill(r,a,hit)}}
function botThink(r){let now=Date.now();for(const b of r.players.values()){if(!b.bot||b.hp<=0)continue;if(now>b.aiNext){b.aiNext=now+220+Math.random()*420;let enemies=[...r.players.values()].filter(p=>p!==b&&!p.bot&&p.team!==b.team&&p.hp>0);if(!enemies.length)enemies=[...r.players.values()].filter(p=>p!==b&&p.team!==b.team&&p.hp>0);let t=enemies.sort((x,y)=>Math.hypot(x.x-b.x,x.z-b.z)-Math.hypot(y.x-b.x,y.z-b.z))[0];if(t){b.aiTarget=t;b.yaw=Math.atan2(t.x-b.x,t.z-b.z);let dx=t.x-b.x,dz=t.z-b.z,d=Math.hypot(dx,dz);if(d>7){b.x+=dx/d*.65;b.z+=dz/d*.65}if(d<38){let dir={x:dx/d,y:(t.y-b.y)/Math.max(1,d),z:dz/d};damage(r,b,{x:b.x,y:b.y,z:b.z},dir)}}}}}
const heartbeat=setInterval(()=>{for(const ws of wss.clients){if(ws.isAlive===false){ws.terminate();continue}ws.isAlive=false;ws.ping()}},30000);
wss.on('connection',ws=>{ws.isAlive=true;ws.on('pong',()=>ws.isAlive=true);send(ws,{type:'hello'});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return send(ws,{type:'error',message:'Invalid message'})};if(m.type==='create'){if(validName(m.username))create(ws,m.username,false);else send(ws,{type:'error',message:'Invalid username'})}else if(m.type==='join'){if(validName(m.username))join(ws,m.username,String(m.code||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase());else send(ws,{type:'error',message:'Invalid username'})}else if(m.type==='quick'){if(!validName(m.username))return send(ws,{type:'error',message:'Invalid username'});let r=[...rooms.values()].find(r=>r.quick&&!r.started&&r.players.size<r.max);r?join(ws,m.username,r.code):create(ws,m.username,true)}else{let p=clients.get(ws);if(!p)return;if(m.type==='start'&&p.host)start(p.room);if(m.type==='input'&&p.room.started&&!p.bot&&p.hp>0){p.x=Math.max(-48,Math.min(48,Number(m.x)||0));p.y=1.7;p.z=Math.max(-48,Math.min(48,Number(m.z)||0));p.yaw=Number(m.yaw)||0;p.pitch=Number(m.pitch)||0}if(m.type==='shoot'&&p.room.started)damage(p.room,p,m.origin,m.dir)}});ws.on('close',()=>{let p=clients.get(ws);if(!p)return;let r=p.room;r.players.delete(p.id);clients.delete(ws);if(p.host){let np=[...r.players.values()].find(x=>!x.bot)||[...r.players.values()][0];if(np){np.host=true;send(np.ws,{type:'hostTransferred',message:'You are now the host.'})}}if(!r.players.size){clearInterval(r.tick);rooms.delete(r.code)}else lobby(r)})});
httpServer.listen(PORT,HOST,()=>console.log(`WARZONE: LAST STAND server v2 running on port ${PORT}`));